### ISSUE TITLE
Swagger integration issue

### ISSUE THREAD

**Issue by leo7** [cdimascio/kotlin-swagger-spring-functional-template#3]
You have all your swagger-ui files copied in https://github.com/cdimascio/kotlin-swagger-spring-functional-template/tree/master/src/main/resources/static.
Is there any better way to do this?

**Comment by cdimascio** [comment]
@leo7 The swagger UI files are not required. I've included them for convenience.
The key file is the `api.yaml`. 
You may host Swagger UI anywhere (including via some other app). Swagger UI enables you to load a spec file via a url.

**Comment by cdimascio** [comment]
For example:
By default, this project sets the spec path is set to `/api.yaml`
![image](https://user-images.githubusercontent.com/4706618/52923236-b6b16980-32f4-11e9-9c30-8446394f8ad6.png)

`/api.yaml` can be set to any url, hence you can host the Swagger UI files elsewhere, including via within some other method.
Note, depending on how you do this, you may have to enable CORS.

**Comment by leo7** [comment]
Thanks @cdimascio for updating and detailed comments :+1: 
I got what you mean. I used to use `springfox swagger` annotations to generate swagger `api-doc` in springboot. But it doesn't support those functional style (routing endpoints) in Spring5. Thought you might have some way to work around it.

**Comment by cdimascio** [comment]
No problem. The key difference between this and SpringFox is that SpringFox will generate the Swagger specification based on annotations in your code. This means you must include numerous annotations within your code to describe a specification. I personally don't like this approach as it leads to stacks of annotations on many methods. 

Instead, this project asks that you write the specification, then it uses that specification to automatically validate your requests and responses

**Comment by cdimascio** [comment]
@leo7 Thanks for your interest in this project. If you have suggestions with respect to how this project can better suit your needs, please send suggestions. I'd love to hear them
